name: lab_gripper
constraints:
  - type: orientation
    weight: 1.0
    frame_id: world
    link_name: tool0
    orientation: [-3.14152927, 0, 0]
    tolerances: [0.001, 0.001, 0.001]
  - type: joint
    joint_name: shoulder_pan_joint
    bounds: [-6.28319, -2.5]
    weight: 1.0
  - type: joint
    joint_name: shoulder_lift_joint
    bounds: [-3.14152, -0.1]
    weight: 1.0
  - type: joint
    joint_name: elbow_joint
    bounds: [-3.14152, -0.1]
    weight: 1.0
  - type: joint
    joint_name: wrist_1_joint
    bounds: [-3.14152, -1.0]
    weight: 1.0
  - type: joint
    joint_name: wrist_2_joint
    position: -1.5708
    tolerance: 0.01
    weight: 1.0
