controller_list:
  - name: fake_manipulator_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_endeffector_controller
    joints:
      - soft_robotics_gripper_left_finger_joint1
      - soft_robotics_gripper_right_finger_joint1
initial: # Define initial robot poses.
  - group: manipulator
    pose: home
  - group: endeffector
    pose: open
